spring:
  application:
    name: MyMall
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=Asia/Shanghai
    #database username and password
    username: root
    password: root
