spring:
  application:
    name: MyMall
  data:
    redis:
      repositories:
        #forbid redis to scan repositories
        enabled: false
      host: localhost
      database: 0
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=Asia/Shanghai
    #database username and password
    username: root
    password: root
oomall:
  core:
    page-size:
      max: 1000
      default: 10
  region:
    timeout: 3600
